// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntry(arg1) {
  return window['go']['main']['App']['AddEntry'](arg1);
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}
